export enum IdentityDocumentTypeEnum {
  DNI = "DNI",
  FOREIGNER_ID_CARD = "FOREIGNER_ID_CARD",
  PASSPORT = "PASSPORT",
  TEMPORARY_RESIDENCE_PERMIT = "TEMPORARY_RESIDENCE_PERMIT",
  TEMPORARY_RESIDENCE_CARD = "TEMPORARY_RESIDENCE_CARD",
  OTHER = "OTHER"
}
