export enum IconEntity {
  CLIENT = 'CLIENT',
  PROJECT = 'PROJECT',
  EQUIPMENT = 'EQUIPMENT',
  CABINET = 'CABINET',
  PANEL = 'PANEL',
  SERVICE = 'SERVICE',
  USER = 'USER',
  SUPERVISOR = 'SUPERVISOR',
  OPERATOR = 'OPERATOR'
}
