export enum InspectableItemTypeEnum {
  COMMUNICATION = 'COMMUNICATION',
  STATE = 'STATE',
  POWER_SUPPLY = 'POWER_SUPPLY',
  POWER_120VAC = 'POWER_120VAC',
  ORDER_AND_CLEANLINESS = 'ORDER_AND_CLEANLINESS',
  OTHERS = 'OTHERS',
}
